<#
.SYNOPSIS
  Write a .env file configuring the ragas-rs LLM/embedding provider.

.DESCRIPTION
  Generates a .env in the repo root that `ProviderConfig::from_env()` reads. Secrets stay
  local (.env is git-ignored). Verify the result with: cargo run --example show_config

.PARAMETER ApiKey
  Chat API key (required). Sent as `Authorization: Bearer <key>`.

.PARAMETER BaseUrl
  Chat endpoint root, e.g. https://api.deepseek.com or https://api.openai.com/v1

.PARAMETER Model
  Chat model id, e.g. deepseek-v4-pro

.PARAMETER EmbeddingBaseUrl / EmbeddingApiKey / EmbeddingModel
  Optional separate embeddings provider (only needed for AnswerRelevancy). Leave unset to
  reuse the chat key/base_url.

.EXAMPLE
  ./scripts/configure-provider.ps1 -ApiKey sk-xxx -BaseUrl https://api.deepseek.com -Model deepseek-v4-pro

.EXAMPLE
  ./scripts/configure-provider.ps1 -ApiKey sk-xxx -BaseUrl https://api.deepseek.com -Model deepseek-v4-pro `
      -EmbeddingBaseUrl https://api.siliconflow.cn/v1 -EmbeddingApiKey sk-yyy -EmbeddingModel Qwen/Qwen3-Embedding-8B
#>
param(
  [Parameter(Mandatory = $true)][string]$ApiKey,
  [string]$BaseUrl = "https://api.openai.com/v1",
  [string]$Model = "gpt-4o-mini",
  [string]$EmbeddingBaseUrl = "",
  [string]$EmbeddingApiKey = "",
  [string]$EmbeddingModel = "",
  [string]$Path = ".env"
)

$lines = @(
  "# Generated by scripts/configure-provider.ps1 — do not commit (git-ignored).",
  "OPENAI_API_KEY=$ApiKey",
  "OPENAI_BASE_URL=$BaseUrl",
  "OPENAI_MODEL=$Model"
)
if ($EmbeddingBaseUrl) { $lines += "OPENAI_EMBEDDING_BASE_URL=$EmbeddingBaseUrl" }
if ($EmbeddingApiKey)  { $lines += "OPENAI_EMBEDDING_API_KEY=$EmbeddingApiKey" }
if ($EmbeddingModel)   { $lines += "OPENAI_EMBEDDING_MODEL=$EmbeddingModel" }

Set-Content -Path $Path -Value $lines -Encoding UTF8
Write-Host "Wrote $Path ($($lines.Count) line(s))."
Write-Host "Verify with: cargo run --example show_config"
